### ISSUE TITLE
Cannot open Viewer application with secure web map

### ISSUE THREAD

**Issue by zwaap** [Esri/arcgis-viewer-silverlight#62]
When a Viewer application takes its map configuration from a non-public web map, the application hangs at the initialization screen unless the login has been cached by the browser.  The user should be prompted to log in.

**Comment by zwaap** [comment]
@pMaske please test

**Comment by pMaske** [comment]
@zwaap Passed QA. Please merge.

**Comment by pMaske** [comment]
Verified.
